Delete user api
kamran-gafoor/Coursepedia-Backend pull request #11
Opened 2023-05-12 02:40 UTC by kamran-gafoor

2023-05-12 02:43 UTC, saahilanande commented on Routes/UserRoute.js
> +      res.send(user);
Send string saying user is Deleted successfully with his id instead of the user object of the deleted user

2023-05-12 02:47 UTC, saahilanande requested changes
Check line 64 for changes

2023-05-14 02:13 UTC, kamran-gafoor commented
Resolved

2023-05-14 02:20 UTC, saahilanande approved these changes
Looks good

2023-05-14 02:21 UTC, merged